### ISSUE TITLE
React 17+ Support

### ISSUE THREAD

**Issue by stplva** [twilio/twilio-video-room-monitor.js#48]
Hi there :)

Unfortunately, there is no support for React v17+ for the @twilio/video-room-monitor package.
It would be really appreciated if you updated dependencies and added support for the newer ReactJS versions.

**Comment by timmydoza** [comment]
Hi @stplva - thanks for the issue!

This is a good idea! I think it's time to make to make the room-monitor compatible with React 17. We'll get started on this and keep you posted.

**Comment by timmydoza** [comment]
Hi @stplva - we've added support for React 17 in #49. Please let us know if there's anything else.

Thanks again!!
